# Generated by Django 3.1.3 on 2020-12-05 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighbourhood',
            name='Photo',
        ),
    ]
