# Generated by Django 3.1.3 on 2020-12-05 14:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_remove_neighbourhood_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='Photo',
            field=cloudinary.models.CloudinaryField(default='photo', max_length=255, verbose_name='hood'),
        ),
    ]
