# Generated by Django 3.1.3 on 2020-12-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbourhood',
            name='photo',
            field=models.ImageField(default='hood.jpg', upload_to='hood'),
        ),
    ]
