# Generated by Django 3.1.3 on 2020-12-05 05:01

import cloudinary.models
import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20201204_2203'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='postPhoto'),
        ),
    ]
