# Generated by Django 3.1.3 on 2020-12-03 11:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0003_neighbourhood_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='hood'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile'),
        ),
    ]
