# Generated by Django 3.1.3 on 2020-12-03 13:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20201203_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='photo',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='businessphoto'),
        ),
    ]
